package org.tpapelita.pojo;

// Generated Apr 19, 2014 10:17:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Administrator generated by hbm2java
 */
@ManagedBean
@SessionScoped
@Entity
@Table(name = "administrator", catalog = "master_tpapelita")
public class Administrator implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer adminId;
	private String adminName;
	private String adminEmail;
	private String adminPhone;
	private Boolean adminGen;
	private String adminJob;
	private String adminPass;
	private String adminLastPass;
	private Boolean status;
	private Set<Event> events = new HashSet<Event>(0);
	private Set<Investment> investments = new HashSet<Investment>(0);

	public Administrator() {
	}

	public Administrator(String adminName, String adminEmail,
			String adminPhone, Boolean adminGen, String adminJob,
			String adminPass, String adminLastPass, Boolean status,
			Set<Event> events, Set<Investment> investments) {
		this.adminName = adminName;
		this.adminEmail = adminEmail;
		this.adminPhone = adminPhone;
		this.adminGen = adminGen;
		this.adminJob = adminJob;
		this.adminPass = adminPass;
		this.adminLastPass = adminLastPass;
		this.status = status;
		this.events = events;
		this.investments = investments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "admin_id", unique = true, nullable = false)
	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	@Column(name = "admin_name", length = 45)
	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	@Column(name = "admin_email", length = 45)
	public String getAdminEmail() {
		return this.adminEmail;
	}

	public void setAdminEmail(String adminEmail) {
		this.adminEmail = adminEmail;
	}

	@Column(name = "admin_phone", length = 14)
	public String getAdminPhone() {
		return this.adminPhone;
	}

	public void setAdminPhone(String adminPhone) {
		this.adminPhone = adminPhone;
	}

	@Column(name = "admin_gen")
	public Boolean getAdminGen() {
		return this.adminGen;
	}

	public void setAdminGen(Boolean adminGen) {
		this.adminGen = adminGen;
	}

	@Column(name = "admin_job", length = 20)
	public String getAdminJob() {
		return this.adminJob;
	}

	public void setAdminJob(String adminJob) {
		this.adminJob = adminJob;
	}

	@Column(name = "admin_pass", length = 65535)
	public String getAdminPass() {
		return this.adminPass;
	}

	public void setAdminPass(String adminPass) {
		this.adminPass = adminPass;
	}

	@Column(name = "admin_last_pass", length = 65535)
	public String getAdminLastPass() {
		return this.adminLastPass;
	}

	public void setAdminLastPass(String adminLastPass) {
		this.adminLastPass = adminLastPass;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "administrator")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "administrator")
	public Set<Investment> getInvestments() {
		return this.investments;
	}

	public void setInvestments(Set<Investment> investments) {
		this.investments = investments;
	}

}
