package org.tpapelita.pojo;

// Generated Apr 29, 2014 11:13:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Administrator generated by hbm2java
 */
@Entity
@Table(name = "administrator", catalog = "master_tpapelita")
public class Administrator implements java.io.Serializable {

	private int adminId;
	private String adminName;
	private String adminEmail;
	private String adminPhone;
	private Boolean adminJob;
	private String adminPass;
	private String adminLastPass;
	private Boolean adminStatus;
	private Set<Investment> investments = new HashSet<Investment>(0);
	private Set<Event> events = new HashSet<Event>(0);
	private Set<Outcome> outcomes = new HashSet<Outcome>(0);

	public Administrator() {
	}

	public Administrator(int adminId) {
		this.adminId = adminId;
	}

	public Administrator(int adminId, String adminName, String adminEmail,
			String adminPhone, Boolean adminJob, String adminPass,
			String adminLastPass, Boolean adminStatus,
			Set<Investment> investments, Set<Event> events,
			Set<Outcome> outcomes) {
		this.adminId = adminId;
		this.adminName = adminName;
		this.adminEmail = adminEmail;
		this.adminPhone = adminPhone;
		this.adminJob = adminJob;
		this.adminPass = adminPass;
		this.adminLastPass = adminLastPass;
		this.adminStatus = adminStatus;
		this.investments = investments;
		this.events = events;
		this.outcomes = outcomes;
	}

	@Id
	@Column(name = "admin_id", unique = true, nullable = false)
	public int getAdminId() {
		return this.adminId;
	}

	public void setAdminId(int adminId) {
		this.adminId = adminId;
	}

	@Column(name = "admin_name", length = 45)
	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	@Column(name = "admin_email", length = 45)
	public String getAdminEmail() {
		return this.adminEmail;
	}

	public void setAdminEmail(String adminEmail) {
		this.adminEmail = adminEmail;
	}

	@Column(name = "admin_phone", length = 14)
	public String getAdminPhone() {
		return this.adminPhone;
	}

	public void setAdminPhone(String adminPhone) {
		this.adminPhone = adminPhone;
	}

	@Column(name = "admin_job")
	public Boolean getAdminJob() {
		return this.adminJob;
	}

	public void setAdminJob(Boolean adminJob) {
		this.adminJob = adminJob;
	}

	@Column(name = "admin_pass", length = 65535)
	public String getAdminPass() {
		return this.adminPass;
	}

	public void setAdminPass(String adminPass) {
		this.adminPass = adminPass;
	}

	@Column(name = "admin_last_pass", length = 65535)
	public String getAdminLastPass() {
		return this.adminLastPass;
	}

	public void setAdminLastPass(String adminLastPass) {
		this.adminLastPass = adminLastPass;
	}

	@Column(name = "admin_status")
	public Boolean getAdminStatus() {
		return this.adminStatus;
	}

	public void setAdminStatus(Boolean adminStatus) {
		this.adminStatus = adminStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "administrator")
	public Set<Investment> getInvestments() {
		return this.investments;
	}

	public void setInvestments(Set<Investment> investments) {
		this.investments = investments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "administrator")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "administrator")
	public Set<Outcome> getOutcomes() {
		return this.outcomes;
	}

	public void setOutcomes(Set<Outcome> outcomes) {
		this.outcomes = outcomes;
	}

}
