package org.tpapelita.pojo;

// Generated Apr 19, 2014 10:17:30 PM by Hibernate Tools 3.4.0.CR1

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InvestmentDetails generated by hbm2java
 */
@ManagedBean
@SessionScoped
@Entity
@Table(name = "investment_details", catalog = "master_tpapelita")
public class InvestmentDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer detailsId;
	private Investment investment;
	private String detailsUnitName;
	private Integer detailsUnitPrice;
	private Integer detailsUnitQty;
	private String detailsInfo;

	public InvestmentDetails() {
	}

	public InvestmentDetails(Investment investment, String detailsUnitName,
			Integer detailsUnitPrice, Integer detailsUnitQty, String detailsInfo) {
		this.investment = investment;
		this.detailsUnitName = detailsUnitName;
		this.detailsUnitPrice = detailsUnitPrice;
		this.detailsUnitQty = detailsUnitQty;
		this.detailsInfo = detailsInfo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "details_id", unique = true, nullable = false)
	public Integer getDetailsId() {
		return this.detailsId;
	}

	public void setDetailsId(Integer detailsId) {
		this.detailsId = detailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inves_id")
	public Investment getInvestment() {
		return this.investment;
	}

	public void setInvestment(Investment investment) {
		this.investment = investment;
	}

	@Column(name = "details_unit_name", length = 50)
	public String getDetailsUnitName() {
		return this.detailsUnitName;
	}

	public void setDetailsUnitName(String detailsUnitName) {
		this.detailsUnitName = detailsUnitName;
	}

	@Column(name = "details_unit_price")
	public Integer getDetailsUnitPrice() {
		return this.detailsUnitPrice;
	}

	public void setDetailsUnitPrice(Integer detailsUnitPrice) {
		this.detailsUnitPrice = detailsUnitPrice;
	}

	@Column(name = "details_unit_qty")
	public Integer getDetailsUnitQty() {
		return this.detailsUnitQty;
	}

	public void setDetailsUnitQty(Integer detailsUnitQty) {
		this.detailsUnitQty = detailsUnitQty;
	}

	@Column(name = "details_info", length = 65535)
	public String getDetailsInfo() {
		return this.detailsInfo;
	}

	public void setDetailsInfo(String detailsInfo) {
		this.detailsInfo = detailsInfo;
	}

}
