package org.tpapelita.pojo;

// Generated May 18, 2014 1:43:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Investment generated by hbm2java
 */
@Entity
@Table(name = "investment", catalog = "master_tpapelita")
public class Investment implements java.io.Serializable {

	private int invesId;
	private Administrator administrator;
	private Investor investor;
	private Date invesDate;
	private Integer invesType;
	private Integer invesStatus;
	private Integer invesTransfer;
	private String invesSenderName;
	private String invesBankName;
	private String invesAccountNo;

	public Investment() {
	}

	public Investment(int invesId) {
		this.invesId = invesId;
	}

	public Investment(int invesId, Administrator administrator,
			Investor investor, Date invesDate, Integer invesType,
			Integer invesStatus, Integer invesTransfer, String invesSenderName,
			String invesBankName, String invesAccountNo) {
		this.invesId = invesId;
		this.administrator = administrator;
		this.investor = investor;
		this.invesDate = invesDate;
		this.invesType = invesType;
		this.invesStatus = invesStatus;
		this.invesTransfer = invesTransfer;
		this.invesSenderName = invesSenderName;
		this.invesBankName = invesBankName;
		this.invesAccountNo = invesAccountNo;
	}

	@Id
	@Column(name = "inves_id", unique = true, nullable = false)
	public int getInvesId() {
		return this.invesId;
	}

	public void setInvesId(int invesId) {
		this.invesId = invesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "admin_id")
	public Administrator getAdministrator() {
		return this.administrator;
	}

	public void setAdministrator(Administrator administrator) {
		this.administrator = administrator;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "investor_id")
	public Investor getInvestor() {
		return this.investor;
	}

	public void setInvestor(Investor investor) {
		this.investor = investor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inves_date", length = 19)
	public Date getInvesDate() {
		return this.invesDate;
	}

	public void setInvesDate(Date invesDate) {
		this.invesDate = invesDate;
	}

	@Column(name = "inves_type")
	public Integer getInvesType() {
		return this.invesType;
	}

	public void setInvesType(Integer invesType) {
		this.invesType = invesType;
	}

	@Column(name = "inves_status")
	public Integer getInvesStatus() {
		return this.invesStatus;
	}

	public void setInvesStatus(Integer invesStatus) {
		this.invesStatus = invesStatus;
	}

	@Column(name = "inves_transfer")
	public Integer getInvesTransfer() {
		return this.invesTransfer;
	}

	public void setInvesTransfer(Integer invesTransfer) {
		this.invesTransfer = invesTransfer;
	}

	@Column(name = "inves_sender_name", length = 45)
	public String getInvesSenderName() {
		return this.invesSenderName;
	}

	public void setInvesSenderName(String invesSenderName) {
		this.invesSenderName = invesSenderName;
	}

	@Column(name = "inves_bank_name", length = 45)
	public String getInvesBankName() {
		return this.invesBankName;
	}

	public void setInvesBankName(String invesBankName) {
		this.invesBankName = invesBankName;
	}

	@Column(name = "inves_account_no", length = 18)
	public String getInvesAccountNo() {
		return this.invesAccountNo;
	}

	public void setInvesAccountNo(String invesAccountNo) {
		this.invesAccountNo = invesAccountNo;
	}

}
