package org.tpapelita.pojo;

// Generated Apr 19, 2014 10:17:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Investor generated by hbm2java
 */
@ManagedBean
@SessionScoped
@Entity
@Table(name = "investor", catalog = "master_tpapelita")
public class Investor implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer investorId;
	private String investorName;
	private String investorEmail;
	private String investorPhone;
	private Boolean investorStatus;
	private Date investorRegistration;
	private String investorPass;
	private String investorLastPass;
	private Set<Investment> investments = new HashSet<Investment>(0);

	public Investor() {
	}

	public Investor(String investorName, String investorEmail,
			String investorPhone, Boolean investorStatus,
			Date investorRegistration, String investorPass,
			String investorLastPass, Set<Investment> investments) {
		this.investorName = investorName;
		this.investorEmail = investorEmail;
		this.investorPhone = investorPhone;
		this.investorStatus = investorStatus;
		this.investorRegistration = investorRegistration;
		this.investorPass = investorPass;
		this.investorLastPass = investorLastPass;
		this.investments = investments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "investor_id", unique = true, nullable = false)
	public Integer getInvestorId() {
		return this.investorId;
	}

	public void setInvestorId(Integer investorId) {
		this.investorId = investorId;
	}

	@Column(name = "investor_name", length = 45)
	public String getInvestorName() {
		return this.investorName;
	}

	public void setInvestorName(String investorName) {
		this.investorName = investorName;
	}

	@Column(name = "investor_email", length = 45)
	public String getInvestorEmail() {
		return this.investorEmail;
	}

	public void setInvestorEmail(String investorEmail) {
		this.investorEmail = investorEmail;
	}

	@Column(name = "investor_phone", length = 14)
	public String getInvestorPhone() {
		return this.investorPhone;
	}

	public void setInvestorPhone(String investorPhone) {
		this.investorPhone = investorPhone;
	}

	@Column(name = "investor_status")
	public Boolean getInvestorStatus() {
		return this.investorStatus;
	}

	public void setInvestorStatus(Boolean investorStatus) {
		this.investorStatus = investorStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "investor_registration", length = 19)
	public Date getInvestorRegistration() {
		return this.investorRegistration;
	}

	public void setInvestorRegistration(Date investorRegistration) {
		this.investorRegistration = investorRegistration;
	}

	@Column(name = "investor_pass", length = 65535)
	public String getInvestorPass() {
		return this.investorPass;
	}

	public void setInvestorPass(String investorPass) {
		this.investorPass = investorPass;
	}

	@Column(name = "investor_last_pass", length = 65535)
	public String getInvestorLastPass() {
		return this.investorLastPass;
	}

	public void setInvestorLastPass(String investorLastPass) {
		this.investorLastPass = investorLastPass;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "investor")
	public Set<Investment> getInvestments() {
		return this.investments;
	}

	public void setInvestments(Set<Investment> investments) {
		this.investments = investments;
	}
}
