package org.tpapelita.pojo;

// Generated May 20, 2014 3:44:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "news", catalog = "master_tpapelita")
public class News implements java.io.Serializable {

	private int newsId;
	private Date newsDate;
	private String newsTitle;
	private String newsContent;
	private Integer adminId;

	public News() {
	}

	public News(int newsId) {
		this.newsId = newsId;
	}

	public News(int newsId, Date newsDate, String newsTitle,
			String newsContent, Integer adminId) {
		this.newsId = newsId;
		this.newsDate = newsDate;
		this.newsTitle = newsTitle;
		this.newsContent = newsContent;
		this.adminId = adminId;
	}

	@Id
	@Column(name = "news_id", unique = true, nullable = false)
	public int getNewsId() {
		return this.newsId;
	}

	public void setNewsId(int newsId) {
		this.newsId = newsId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "news_date", length = 19)
	public Date getNewsDate() {
		return this.newsDate;
	}

	public void setNewsDate(Date newsDate) {
		this.newsDate = newsDate;
	}

	@Column(name = "news_title", length = 25)
	public String getNewsTitle() {
		return this.newsTitle;
	}

	public void setNewsTitle(String newsTitle) {
		this.newsTitle = newsTitle;
	}

	@Column(name = "news_content", length = 65535)
	public String getNewsContent() {
		return this.newsContent;
	}

	public void setNewsContent(String newsContent) {
		this.newsContent = newsContent;
	}

	@Column(name = "admin_id")
	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

}
