package org.tpapelita.pojo;

// Generated May 18, 2014 3:44:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SupportCenter generated by hbm2java
 */
@Entity
@Table(name = "support_center", catalog = "master_tpapelita")
public class SupportCenter implements java.io.Serializable {

	private Integer supportId;
	private Date supportDate;
	private String supportName;
	private String supportSubject;
	private String supportEmail;
	private String supportMessage;
	private Boolean supportShow;
	private Integer supportStatus;

	public SupportCenter() {
	}

	public SupportCenter(Date supportDate, String supportName,
			String supportSubject, String supportEmail, String supportMessage,
			Boolean supportShow, Integer supportStatus) {
		this.supportDate = supportDate;
		this.supportName = supportName;
		this.supportSubject = supportSubject;
		this.supportEmail = supportEmail;
		this.supportMessage = supportMessage;
		this.supportShow = supportShow;
		this.supportStatus = supportStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "support_id", unique = true, nullable = false)
	public Integer getSupportId() {
		return this.supportId;
	}

	public void setSupportId(Integer supportId) {
		this.supportId = supportId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "support_date", length = 19)
	public Date getSupportDate() {
		return this.supportDate;
	}

	public void setSupportDate(Date supportDate) {
		this.supportDate = supportDate;
	}

	@Column(name = "support_name", length = 35)
	public String getSupportName() {
		return this.supportName;
	}

	public void setSupportName(String supportName) {
		this.supportName = supportName;
	}

	@Column(name = "support_subject", length = 20)
	public String getSupportSubject() {
		return this.supportSubject;
	}

	public void setSupportSubject(String supportSubject) {
		this.supportSubject = supportSubject;
	}

	@Column(name = "support_email", length = 50)
	public String getSupportEmail() {
		return this.supportEmail;
	}

	public void setSupportEmail(String supportEmail) {
		this.supportEmail = supportEmail;
	}

	@Column(name = "support_message", length = 65535)
	public String getSupportMessage() {
		return this.supportMessage;
	}

	public void setSupportMessage(String supportMessage) {
		this.supportMessage = supportMessage;
	}

	@Column(name = "support_show")
	public Boolean getSupportShow() {
		return this.supportShow;
	}

	public void setSupportShow(Boolean supportShow) {
		this.supportShow = supportShow;
	}

	@Column(name = "support_status")
	public Integer getSupportStatus() {
		return this.supportStatus;
	}

	public void setSupportStatus(Integer supportStatus) {
		this.supportStatus = supportStatus;
	}

}
